[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0
pidfile=/www/storage/logs/supervisord.pid
loglevel=info

[program:octane]
directory=/www
command=php artisan octane:start --server=swoole --host=127.0.0.1 --port=7002 --workers=2 --task-workers=2 --max-requests=1000
autostart=true
autorestart=true
user=www
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=10
stopsignal=QUIT
stopasgroup=true
killasgroup=true
priority=100

[program:horizon]
directory=/www
command=php artisan horizon
autostart=true
autorestart=true
user=www
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3
stopsignal=SIGINT
stopasgroup=true
killasgroup=true
priority=200

[program:ws-server]
directory=/www
command=php artisan ws-server start --host=127.0.0.1 --port=8076
autostart=true
autorestart=true
user=www
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=5
stopsignal=SIGINT
stopasgroup=true
killasgroup=true
priority=300

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
user=root
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=5
priority=400